EMPTY = 8

WHITE_PAWN = 0
WHITE_PAWN_EN_PASSANT = 1

WHITE_ROOK = 2
WHITE_KNIGHT = 3
WHITE_BISHOP = 4
WHITE_QUEEN = 5
WHITE_KING = 6

WHITE_MIN = 0
WHITE_MAX = 8

BLACK_PAWN = 16
BLACK_PAWN_EN_PASSANT = 15

BLACK_ROOK = 14
BLACK_KNIGHT = 13
BLACK_BISHOP = 12
BLACK_QUEEN = 11
BLACK_KING = 10

BLACK_MIN = 10
BLACK_MAX = 17

INIT_STATE = 64*[EMPTY] + [True, True, True, True]

INIT_STATE[0] = WHITE_ROOK
INIT_STATE[1] = WHITE_KNIGHT
INIT_STATE[2] = WHITE_BISHOP
INIT_STATE[3] = WHITE_QUEEN
INIT_STATE[4] = WHITE_KING
INIT_STATE[5] = WHITE_BISHOP
INIT_STATE[6] = WHITE_KNIGHT
INIT_STATE[7] = WHITE_ROOK

INIT_STATE[8:16] = 8*[WHITE_PAWN]

INIT_STATE[63] = BLACK_ROOK
INIT_STATE[62] = BLACK_KNIGHT
INIT_STATE[61] = BLACK_BISHOP
INIT_STATE[60] = BLACK_KING
INIT_STATE[59] = BLACK_QUEEN
INIT_STATE[58] = BLACK_BISHOP
INIT_STATE[57] = BLACK_KNIGHT
INIT_STATE[56] = BLACK_ROOK

INIT_STATE[48:56] = 8*[BLACK_PAWN]

symbols = dict()
symbols[EMPTY] = " "
symbols[WHITE_PAWN] = "♙"
symbols[WHITE_PAWN_EN_PASSANT] = "♙"
symbols[WHITE_ROOK] = "♖"
symbols[WHITE_BISHOP] = "♗"
symbols[WHITE_KNIGHT] = "♘"
symbols[WHITE_QUEEN] = "♕"
symbols[WHITE_KING] = "♔"

symbols[BLACK_PAWN] = "♟"
symbols[BLACK_PAWN_EN_PASSANT] = "♟"
symbols[BLACK_ROOK] = "♜"
symbols[BLACK_BISHOP] = "♝"
symbols[BLACK_KNIGHT] = "♞"
symbols[BLACK_QUEEN] = "♛"
symbols[BLACK_KING] = "♚"
